services:
  web:
    build:
      context: ../web
      dockerfile: Dockerfile
      target: dev
    environment:
      - NODE_ENV=development
    volumes:
      - ../web:/app
      - /app/node_modules
      - /app/.next
