#
# Runs on push to master, does typecheck, updates semver and then triggers a Portainer stack update via webhook
#

name: Push workflow

on:
  push:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semver:
    name: Calculate and update semantic version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        project: [web]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Calculate and update semantic version
        uses: ./.github/actions/semver
        with:
          project: ${{ matrix.project }}

  typecheck:
    name: Run code typecheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        project: [web]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run typecheck
        uses: ./.github/actions/typecheck
        with:
          project: ./${{ matrix.project }}

  deploy:
    needs: [semver, typecheck]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Trigger Portainer stack update
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.PORTAINER_WEBHOOK_URL }}
          timeout: 600 # 10m - Webhook doesn't respond until deployment is done (it can take a few minutes)
